Add read_version.py
avatar-project/avatar-services-toolkit pull request #11
Opened 2020-10-01 10:16 UTC by ArtemDavletov

Add read_version.py

2020-10-05 12:16 UTC, hainamantik requested changes

2020-10-05 12:16 UTC, hainamantik commented on services_toolkit/validation/read_version.py
> +    if not os.path.isfile:
Проверка чего это?
```python
>>> from os.path import isfile
>>> isfile
<function isfile at 0x7fd8f6665ee0>
```
Сейчас в новых проектах/версиях питона активно используется библиотека pathlib, она удобнее. [Нужная функция.](https://docs.python.org/3/library/pathlib.html#pathlib.Path.exists)

2020-10-19 13:22 UTC, ArtemDavletov commented on services_toolkit/validation/read_version.py
> +    if not os.path.isfile:
Done

2020-10-28 15:16 UTC, hainamantik commented
Оставить только этот код в сравнении с мастером, все остальные изменения откатить
```python

from logging import getLogger
from pathlib import Path

logger = getLogger(__name__)


def read_version(path: str):
    if not Path(path).exists():
        return '0.0.0'

    with open(path, encoding='utf-8') as file:
        version = file.readline().strip()
        logger.info('Current version: %s', version)

        return version
```

2020-10-28 15:29 UTC, hainamantik approved these changes

2020-10-28 15:31 UTC, merged